### ISSUE TITLE
Can't Compose New Messages

### ISSUE THREAD

**Issue by countryathlon** [moezbhatti/qksms#1588]
I can't compose text messages to anyone unless I select an existing message thread.

### STEPS
1. Open qksms+ (ver. 3.8.0 or 3.8.1)
2. Tap the "+" to compose new message
3. Select a contact in the contacts list

### EXPECTED
Selecting a contact in the list should allow composing a text message to that person.

### OBSERVATIONS
Selecting a contact simply returns to the contact list instead of composing a message to that contact.

I have tried a lot of things, including syncing the message list, Uninstall/re-installed the app, deleted all data, and verified permissions.
I have an LG V20 with Android 8.0.0.
Downgrade to Ver. 3.7.10 works properly.

**Comment by alaskalinuxuser** [comment]
I also have this issue with 3.8.1, except when I choose a contact, it changes to a  different contact to send the text to. It ironically always chooses the same wrong contact to send to. This contact is not first or last on my contact list, and it is not a contact I have text recently, nor is it a contact that I already have an open thread on.

I could reply to any open thread without issue.

Android 10 aosp Sony discovery (xa2 ultra).

I also reverted to 3.7.x where everything works as expected.

Love qksms and all the great work you do!

**Comment by moezbhatti** [comment]
I believe this should be fixed now. If anyone wants to try a test build:

[QKSMS-v3.8.1-noAnalytics-debug.apk.zip](https://github.com/moezbhatti/qksms/files/4606304/QKSMS-v3.8.1-noAnalytics-debug.apk.zip)

**Comment by countryathlon** [comment]
Thanks!  When I go to install this test build, it simply says "App Not Installed"

**Comment by moezbhatti** [comment]
This is a debug build, so unfortunately you'll need to uninstall your existing version before you can install this

After you test it, you'll want to switch back to your old build as well, so that you can get automatic updates

**Comment by countryathlon** [comment]
Uh oh, after removing the old version completely and restarting the phone, this version will still not install..  During install this time, it paused for some time at about 90% complete before saying not installed.  With the old version still there, it was almost instantaneous.

**Comment by moezbhatti** [comment]
Oh, very strange. Tomorrow I'll put together another build which I think should work - feel free to install the prod build in the meantime

**Comment by moezbhatti** [comment]
Alright - you should be able to install this one as an update to the prod build. If you want to switch back after testing, I think you can just install the v3.8.1 APK from the Releases page back on top of this

[QKSMS-1588-Bugfix.apk.zip](https://github.com/moezbhatti/qksms/files/4613108/QKSMS-1588-Bugfix.apk.zip)

**Comment by countryathlon** [comment]
Unfortunately, the behavior is still the same for some reason -I tried installing on top of the old 3.7.10 version; I also uninstalled the old version and tried it: app not installed.

**Comment by moezbhatti** [comment]
Any chance you could get a video recording of the issue?

**Comment by countryathlon** [comment]
Of not being able to install the test builds?  It is really simple, I unzip the .apk and run it.  A familiar mostly white screen appears asking if I want to install -I tap the install button on the lower right-hand corner.  The installation progress bar appears briefly and is replaced by a very simple white screen with a gray triangle/exclamation that says "App not installed" below it -then the only option is to tap "done" at the bottom.

**Comment by GeoZac** [comment]
> Of not being able to install the test builds? It is really simple, I unzip the .apk and run it. A familiar mostly white screen appears asking if I want to install -I tap the install button on the lower right-hand corner. The installation progress bar appears briefly and is replaced by a very simple white screen with a gray triangle/exclamation that says "App not installed" below it -then the only option is to tap "done" at the bottom.

You have uninstalled all qksms builds before trying this install or you're trying to update an exisiting app?

**Comment by moezbhatti** [comment]
Oh, sorry, I misread your comment. I thought that you said it installed, but the compose issue still persisted

**Comment by countryathlon** [comment]
@GeoZac Yes, I did try both for good measure (above).
