### ISSUE TITLE
The attached images will not be displayed

### ISSUE THREAD

**Issue by Fabrice35** [moezbhatti/qksms#603]
When editing a new message, attached images are not displayed.

**Comment by moezbhatti** [comment]
Can you post some details about your phone / android version / qksms version?

**Comment by Fabrice35** [comment]
Samsung S5 NEO / Android 6.0.1 / QKSMS 2.7.1

**Comment by moezbhatti** [comment]
This has been fixed in QKSMS 3.0

**Comment by Fabrice35** [comment]
Thanks a lot !
Do you know when this new version will be released?

**Comment by moezbhatti** [comment]
No problem! Preview releases are currently available here: https://github.com/moezbhatti/qksms/releases

I am hoping to launch the full version on the Play Store in the next 2-3 weeks however

**Comment by otede** [comment]
Still facing the same problem. Latest app version, Android 7.1.x (LineageOS) on Moto X Play.

**Comment by moezbhatti** [comment]
Hmm, this seems different than the other problem you described, @otede. Can you just confirm what's happening here in your own words? I just want to be sure I'm understanding your issue correctly

**Comment by otede** [comment]
> Hmm, this seems different than the other problem you described, @otede. Can you just confirm what's happening here in your own words? I just want to be sure I'm understanding your issue correctly

After I'm returned to QKSMS (after selecting an image to be attached) the input field expands, clearly making space for the image thumbnail. The thumbnail is not present though, even though an X is visible on the supposed corner. Only the background is seen. In my case - white.
